# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
     - bash: echo $(Build.BuildNumber)
     - bash: echo $(Build.BuildId)
     - bash: echo $(Build.SourceBranchName)
     - bash: echo $(Build.SourceDirectory)
     - bash: echo $(System.DefaultWorkingDirectory)
     - bash: ls -R $(System.DefaultWorkingDirectory)
     - bash: echo $(Build.ArtifactStagingDirectory)
     - bash: echo Build FirstJobInBuild
     - bash: echo $(pipelinelevelvariable)
  - job: SecondJob
    steps:
    - bash: echo Build SecondJobInBuild
- stage: DevDeploy
  variables:
    environment: Dev
  dependsOn: Build
  jobs:
  - job: DevDeployJob
    steps:
     - bash: echo Build DevDeployJob
     - bash: echo $(environment)DevDeployJob
- stage: QADeploy
  dependsOn: DevDeploy
  jobs:
  - job: QADeployJob
    steps:
     - bash: echo Build QADeployJob

